version: '3'
services:
  gitolite:
    build: .
    environment:
      - ADMIN_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5t6a+BxJBObivLIu2Q7NnAAj6SspatQT1KpjOagstq5YBbFDycIt0Z8CUmNOFMpr8lBDAhH7J+HHEM9OzmfH4HdwvRim9lPo++bMCSPacvdIjC7gkEWNYSrINSAw6ADQrt+tTF67RwYpeWKPyUHH5K/FXTWcmfIv3YhgzWD8BVh2MV5yfLvCn0613pSWsB/jpZa+xoxDCQ6hVPIs4VyDps9iPn4tvt2p9l7Ord6XuizxnNVdxJNH78BW4NEp73YvgLg0gsGSEXySOO0R09QaOaVF9EidpuehjKIGJNuMgsxhZC0hnyPSMYvEDLk9fpWP/HEIFjO73e0pz32nAqBE/afQIDy8qS3tqpY2Eft64UxNXtGKS2pUPsVzsbPtsFrlNbZAKoUAla7D7azxwpIQFwFZFiKaKUUalyflPjnYoDVZt7K1MmtCIBg4eGdvGKU2CsmXUQw/MkA/42lPB8/9zS0CQuxb6vXTWVehvKFXsNCAQIIJLrRcXdfAE++9jXlvMFFHJjtbeyjieU3MKQeKBh++StEs/544ffBak6T0fQeTrbB8O9ssi4caSgudOZ2xHZ3Yy2h6TawYKbNEIvK+5COd4MD0P+8Atm00pIiRNi+/bsGZJTA4yfsLzKkDmBHsH1n7/qdbSpWkBzwoLyDvyjGxv+gO/EdnWmUNKHXWv7Q== cardno:000613143129
    ports:
      - "2222:22"
    volumes:
      - gitdata:/home/git
volumes:
  gitdata:
